### ISSUE TITLE
布局

### ISSUE THREAD

**Issue by caoxinhui** [caoxinhui/Diary#10]
#### 伪元素
```html
<style>
    .container {
        background-color: #00acec;
    }
    .container::before{
        content: '';
        float: left;
        padding-bottom: 50%;
    }
    .container::after{
        clear: both;
        content: '';
        display: table;
    }
</style>

<div class="container">
```
#### 内容绝对定位
```html
<style>
    .container {
        background-color: #00acec;
        overflow: hidden;
        padding-top: 50%;
        position: relative;
        height: 0;
    }
    .content{
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
    }

</style>

<div class="container">
    <div class="content"></div>
</div>
```
#### 视窗单位vw/vh
```html
<style>
    .container {
        background-color: #00acec;
        width: 100vw;
        height: 50vw;
    }
</style>

<div class="container">
</div>
```
```html
<style>
    .container {
        background-color: #00acec;
        width: 100vh;
        height: 50vh;
    }
</style>

<div class="container">
</div>
```
#### 方法1 

DOM 结构
```html
<div class="wrapper">
    <div class="header"></div>
    <div class="content">
        <div class="left">左边</div>
        <div class="middle">中间</div>
        <div class="right">右边</div>
    </div>
    <div class="footer"></div>
</div>
```
```css
.header, .footer {
    background: green;
    width: 100%;
    height: 40px;
}
.content{
    display: flex;
}
.left{
    width: 200px;
    background-color: yellow;
}
.middle{
    flex: 1;
    background-color: pink;
}
.right{
    width: 300px;
    background-color: aqua;
}
```
#### 方法2
DOM结构
```html
<div class="wrapper">
    <div class="header"></div>
    <div class="container">
        <div class="middle">中间</div>
        <div class="left">左边</div>
        <div class="right">右边</div>
    </div>
    <div class="footer"></div>
</div>
```

```css
.header, .footer {
    background: green;
    width: 100%;
    height: 40px;
}
.footer{
    clear: both;
}
.container {
    padding-left: 200px;
    padding-right: 250px;
}
.container div {
    position: relative;
    float: left;
}
.left {
    width: 200px;
    background: yellow;
    margin-left: -100%;
    left: -200px;
}
.middle{
    width: 100%;
    background-color: pink;
}
.right {
    width: 250px;
    background: aqua;
    margin-left: -250px;
    left: 250px;
}
```

#### 方法3
DOM结构
```html
<div class="wrapper">
    <div class="header"></div>
    <div class="container">
        <div class="left">左边</div>
        <div class="right">右边</div>
        <div class="middle">中间</div>
    </div>
    <div class="footer"></div>
</div>
```
```css
*{
    margin: 0;
    padding: 0;
}
.header, .footer {
    background: green;
    width: 100%;
    height: 40px;
}


.container{
    overflow: hidden;
}
.left {
    width: 200px;
    background: yellow;
    float: left;
}
.middle{
    width: 100%;
    background-color: pink;
}
.right {
    width: 250px;
    background: aqua;
    float: right;
}
```

#### 方法4
绝对定位

DOM结构同上
```css
*{
    margin: 0;
    padding: 0;
}
.header, .footer {
    background: green;
    width: 100%;
    height: 40px;
}


.container{
    position: relative;
}
.container div{
    position: absolute;
}
.left {
    width: 200px;
    background: yellow;
    left: 0;
}
.middle{
    left: 200px;
    right: 250px;
    background-color: pink;
}
.right {
    width: 250px;
    background: aqua;
    right: 0;
}
```
