### ISSUE TITLE
CSS 水平垂直居中

### ISSUE THREAD

**Issue by caoxinhui** [caoxinhui/Diary#8]
## 水平居中
[原文链接](http://47.98.159.95/my_blog/css/001.html#%E6%B0%B4%E5%B9%B3%E5%B1%85%E4%B8%AD)
### 行内元素
> text-align 写在div中，div中的行内元素水平居中
```html
<style>
    .parent {
        width: 500px;
        height: 500px;
        border: 1px solid black;
        text-align: center;
    }

    .child {
        border: 1px solid red;
        height: 100px;
    }
</style>
<div class="parent">
    <span class="child">块级框</span>
</div>
```

### 确定宽度的块元素
```html
<style>
    .parent{
        width: 500px;
        height: 500px;
        border: 1px solid black;
    }
    .text{
        border: 1px solid red;
        width: 100px;
        margin: 0 auto;
        height: 100px;
    }
</style>


<div class="parent">
    <div class="text"></div>
</div>
```

### 宽度未知的块级元素
- 方法1
```html
<style>
    .parent{
        width: 500px;
        height: 500px;
        border: 1px solid black;
    }
    .child{
        border: 1px solid red;
        display: table;
        margin: 0 auto;
    }
</style>


<div class="parent">
    <div class="child">块级框</div>
</div>
```

- 方法2
```html
<style>
    .parent{
        width: 500px;
        height: 500px;
        border: 1px solid black;
        text-align: center;
    }
    .child{
        border: 1px solid red;
        display: inline-block;
        width: 100px;
    }
</style>


<div class="parent">
    <div class="child">块级框</div>
</div>
```

- 方法3
```html
<style>
    .parent{
        width: 500px;
        height: 500px;
        border: 1px solid black;
        display: flex;
        justify-content: center;
    }
    .child{
        border: 1px solid red;
    }
</style>


<div class="parent">
    <div class="child">块级框</div>
</div>
```

- 方法4
```css
.parent{
    position: relative;
    height:1.5em;
}
.child{
    position: absolute;
    left: 50%;
    transform: translateX(-50%);
}
```

```html
<style>
    .parent{
        width: 500px;
        height: 500px;
        border: 1px solid black;
        position: relative;
    }
    .child{
        border: 1px solid red;
        position: absolute;
        left: 50%;
        transform: translateX(-50%);
    }
</style>
<div class="parent">
    <div class="child">块级框</div>
</div>
```

- 方法5
> 适用于 child 定宽

```css
.parent{
    position: relative;
    height:1.5em;
}
.child{
    position: absolute;
    width:100px;
    left: 50%;
    margin-left:-50px;
}
```

```html
<style>
    .parent{
        width: 500px;
        height: 500px;
        border: 1px solid black;
        position: relative;
    }
    .child{
        border: 1px solid red;
        position: absolute;
        left: 50%;
        width:100px;
        left: 50%;
        margin-left:-50px;
    }
</style>
<div class="parent">
    <div class="child">块级框</div>
</div>
```

## 垂直居中
- 方法1
```css
.parent{
	display: table-cell;
	vertical-align: middle;
}
```

```html
<style>
    .parent{
        width: 500px;
        height: 500px;
        border: 1px solid black;
        display: table-cell;
        vertical-align: middle;
    }
    .child{
        border: 1px solid red;
    }

</style>
<div class="parent">
    <div class="child">块级框</div>
</div>
```
- 方法2
```css
.parent {
        display: flex;
    }

    .child {
        margin: auto;
    }
```

```html
<style>
    .parent{
        width: 500px;
        height: 500px;
        border: 1px solid black;
        display: flex;
    }
    .child{
        border: 1px solid red;
        margin: auto;
    }

</style>
<div class="parent">
    <div class="child">块级框</div>
</div>
```

- 方法3
```html
<style>
    .parent {
        height:500px;
        text-align: center;
        border: 1px solid black;
    }
    .parent:before {
        content: '';
        display: inline-block;
        height: 100%;
        vertical-align: middle;
        border: 1px solid yellow;
    }
    .child {
        border: 1px solid red;
        display: inline-block;
        vertical-align: middle;
    }
</style>

<div class="parent">
    <div class="child">
        Centered Content
    </div>
</div>
```

- 方法4
```css
.parent{
	position: relative;
}
.child{
	position: absolute;
	top: 50%;
	transform: translateY(-50%);
}
```

```html
<style>
    .parent {
        width: 500px;
        height: 500px;
        border: 1px solid black;
        display: flex;
        position: relative;
    }
    .child {
        border: 1px solid red;
        position: absolute;
        top: 50%;
        transform: translateY(-50%);
    }

</style>
<div class="parent">
    <div class="child">块级框</div>
</div>
```

- 方法5
```css
.parent{
	display: flex;
	align-items: center;
}
```
```html
<style>
    .parent {
        width: 500px;
        height: 500px;
        border: 1px solid black;
        display: flex;
        align-items: center;

    }

    .child {
        border: 1px solid red;
    }

</style>
<div class="parent">
    <div class="child">块级框</div>
</div>
```

### 定宽高
```html
<style>
    .container {
        width: 500px;
        height: 500px;
        border: 1px solid black;
        position: relative;
    }
    .child{
        border: 1px solid red;
        position: absolute;
        left: 0;
        right: 0;
        top: 0;
        bottom: 0;
        margin: auto;
        width: 100px;
        height: 50px;
    }
</style>

<div class="container">
    <div class="child">内容区域</div>
</div>
```
- 方法1
```css
.parent{
	text-align: center;
	display: table-cell;
	vertical-align: middle;
}
.child{
	display: inline-block;
}
```

```html
<style>
    .parent {
        width: 500px;
        height: 500px;
        border: 1px solid black;
        text-align: center;
        display: table-cell;
        vertical-align: middle;
    }
    .child {
        border: 1px solid red;
        display: inline-block;
    }
</style>
<div class="parent">
    <div class="child">块级框</div>
</div>
```

- 方法2
```css
.parent{
	position: relative;
}
.child{
	position: absolute;
	left: 50%;
	top: 50%;
	transform: translate(-50%,-50%);
}
```

```html
<style>
    .parent {
        width: 500px;
        height: 500px;
        border: 1px solid black;
        position: relative;
    }
    .child {
        border: 1px solid red;
        position: absolute;
        left: 50%;
        top: 50%;
        transform: translate(-50%,-50%);
    }
</style>
<div class="parent">
    <div class="child">块级框</div>
</div>
```
- 方法3
```css
.parent{
	display: flex;
	justify-content: center;
	align-items: center;
}
```

```html
<style>
    .parent {
        width: 500px;
        height: 500px;
        border: 1px solid black;
        display: flex;
        justify-content: center;
        align-items: center;
    }
    .child {
        border: 1px solid red;

    }
</style>
<div class="parent">
    <div class="child">块级框</div>
</div>
```
- grid布局
```html
<body>
<style>
    .outer {
        display: grid;
        width: 300px;
        height: 300px;
        background: red;
    }

    .inner {
        width: 200px;
        height: 200px;
        align-self: center;
        justify-self: center;
        background: yellow;
    }
</style>
<div class="outer">
    <div class="inner"></div>
</div>
</body>
```

```html
<body>
<style>
    .outer {
        display: grid;
        align-content: center;
        justify-content: center;
        width: 300px;
        height: 300px;
        background: red;
    }

    .inner {
        width: 200px;
        height: 200px;
        background: yellow;
    }
</style>
<div class="outer">
    <div class="inner"></div>
</div>
</body>
```
### 左边定宽，右边自适应 
- float+margin
```css
.left{
	float: left;
	width: 100px;
}
.right{
	margin-left: 120px;
}
```

```html
<style>
    .container{
        border: 2px dashed blue;
    }
    .left {
        width: 500px;
        border: 1px solid black;
        float: left;
    }
    .right {
        border: 1px solid red;
        margin-left: 500px;
    }
</style>
<div class="container">
    <div class="left">左边区域</div>
    <div class="right">右边区域</div>
</div>
```
- float+overflow
```css
.left{
	float: left;
	width: 100px;
}
.right{
	overflow: hidden;
}
```

```html
<style>
    .container{
        border: 2px dashed blue;
    }
    .left {
        width: 500px;
        border: 1px solid black;
        float: left;
    }
    .right {
        border: 1px solid red;
        overflow: hidden;
    }
</style>
<div class="container">
    <div class="left">左边区域</div>
    <div class="right">右边区域</div>
</div>
```

- table
```css
.container{
	display: table; 
    width: 100%;
	table-layout: fixed;
}
.left,.right{
	display: table-cell;
}
.left{
	width: 100px;
}
```
```html
<style>
    .container{
        border: 2px dashed blue;
        display: table;
        width: 100%;
        table-layout: fixed;
    }
    .left {
        width: 100px;
        border: 1px solid black;
        display: table-cell;
        padding-right: 20px;
    }
    .right {
        border: 1px solid red;
        display: table-cell;
    }
</style>
<div class="container">
    <div class="left">左边区域</div>
    <div class="right">右边区域</div>
</div>
```

- flex

```css
.container{
        display: flex;
    }
    .left {
        width: 100px;

    }
    .right {
        flex: 1;
    }
```
```html
<style>
    .container{
        border: 2px dashed blue;
        display: flex;
    }
    .left {
        width: 100px;
        border: 1px solid black;

    }
    .right {
        border: 1px solid red;
        flex: 1;
    }
</style>
<div class="container">
    <div class="left">左边区域</div>
    <div class="right">右边区域</div>
</div>
```

### 多列定宽，一列自适应
- flex
```css
.container{
	display: flex;
}
.left,.center{
	width: 100px;
}
.right{
	flex: 1;
}
```
```html
<style>
    .container{
        border: 2px dashed blue;
        display: flex;
    }
    .left,.center {
        width: 100px;
        border: 1px solid black;

    }
    .right {
        border: 1px solid red;
        flex: 1;
    }
</style>
<div class="container">
    <div class="left">左边区域</div>
    <div class="center">中间区域</div>
    <div class="right">右边区域</div>
</div>
```

- float+overflow
```css
.left,.center{
	float: left;
	width: 100px;
}
.right{
	overflow: hidden;
}
```
```html
<style>
    .container{
        border: 2px dashed blue;
    }
    .left,.center {
        float: left;
        width: 100px;
        border: 1px solid red;
    }
    .right {
        overflow: hidden;
        border: 1px solid red;
    }
</style>
<div class="container">
    <div class="left">左边区域</div>
    <div class="center">中间区域</div>
    <div class="right">右边区域</div>
</div>
```
- table
```html
<style>
    .container {
        border: 2px dashed blue;
        display: table;
        width: 100%;
        table-layout: fixed;
    }

    .left, .center, .right {
        display: table-cell;
        border: 1px solid red;
    }

    .left,.center {
        width: 100px;
        border: 1px solid red;
    }
</style>
<div class="container">
    <div class="left">左边区域</div>
    <div class="center">中间区域</div>
    <div class="right">右边区域</div>
</div>
```

### 一列不定宽，一列自适应
```css
.right {
    overflow: hidden;
}
.left {
    float: left;
}
```
```html
<style>
    .container {
        border: 2px dashed blue;
    }

    .right {
        overflow: hidden;
        border: 1px solid red;
    }

    .left {
        float: left;
        border: 1px solid red;
    }
</style>
<div class="container">
    <div class="left">左边区域对的</div>
    <div class="right">右边区域</div>
</div>
```

- table
```css
.container {
    display: table;
    width: 100%;
}
.left {
    width: 10%;
}
.left,.right {
    display: table-cell;
}
```
```html
<style>
    .container {
        border: 2px dashed blue;
        display: table;
        width: 100%;
    }
    .left {
        width: 10%;
        border: 1px solid red;
    }
    .left,.right {
        display: table-cell;
        border: 1px solid red;
    }
</style>
<div class="container">
    <div class="left">左边区域对的</div>
    <div class="right">右边区域</div>
</div>
```

- flex
```css
.container {
    display: flex;
}
.left {
    width: 200px;
}
.right{
    flex: 1;
}
```
```html
<style>
    .container {
        border: 2px dashed blue;
        display: flex;
    }
    .left {
        width: 200px;
        border: 1px solid red;
    }

    .right{
        flex: 1;
        border: 1px solid black;
    }
</style>
<div class="container">
    <div class="left">左边区域对的</div>
    <div class="right">右边区域</div>
</div>
```

### 多列不定宽，一列自适应
```css
.left,.center {
    float: left;
}
.right{
    overflow: hidden;
}
```
```html
<style>
    .container {
        border: 2px dashed blue;
    }
    .left,.center {
        float: left;
        border: 1px solid red;
    }

    .right{
        overflow: hidden;
        border: 1px solid black;
    }
</style>
<div class="container">
    <div class="left">左边区域对的</div>
    <div class="center">中间区域</div>
    <div class="right">右边区域</div>
</div>
```

### 等分
- float+margin
```css
.parent {
    margin-left: -20px;
}
.column{
    float: left;
    width: 25%;
    padding-left: 20px;
    box-sizing: border-box;
}
```
```html
<style>
    .parent {
        margin-left: -20px;
        border: 2px dashed blue;
        overflow: hidden;
    }
    .column{
        float: left;
        width: 25%;
        padding-left: 20px;
        box-sizing: border-box;
        height: 100px;
        border: 1px solid yellow;
    }
</style>
<div class="parent">
    <div class="column">1</div>
    <div class="column">2</div>
    <div class="column">3</div>
    <div class="column">4</div>
</div>
```

- table+margin
```css
.parent {
    display: table;
    table-layout: fixed;
    width: 100%;
}
.column{
    display: table-cell;
    padding-left: 20px;
}
```
```html
<style>
    .parent {
        border: 2px dashed blue;
        display: table;
        table-layout: fixed;
        width: 100%;
    }
    .column{
        display: table-cell;
        padding-left: 20px;
        border: 1px solid black;
    }
</style>
<div class="parent">
    <div class="column">1</div>
    <div class="column">2</div>
    <div class="column">3</div>
    <div class="column">4</div>
</div>
```
- flex
```css
.parent {
    border: 2px dashed blue;
    display: flex;
}

.column {
    flex: 1;
    border: 1px solid black;
}
```

```html
<style>
    .parent {
        border: 2px dashed blue;
        display: flex;
    }

    .column {
        flex: 1;
        border: 1px solid black;
    }
</style>
<div class="parent">
    <div class="column">1</div>
    <div class="column">2</div>
    <div class="column">3</div>
    <div class="column">4</div>
</div>
```

### 等高
- float+overflow
🤔不对啊
```html
<style>
    .parent {
        border: 2px dashed blue;
        overflow: hidden;
    }

    .left, .right {
        padding-bottom: 9999px;
        margin-bottom: -9999px;
    }
    .left{
        float: left;
        width: 100px;
        border: 1px solid red;
    }
    .right{
        overflow: hidden;
        border: 1px solid black;
    }
</style>
<div class="parent">
    <div class="left">1</div>
    <div class="right">2</div>
    <div class="right">3</div>
</div>
```

- table
```html
<style>
    .parent {
        border: 2px dashed blue;
        display: table;
        width: 100%;
    }


    .left{
        display: table-cell;
        width: 100px;
        border: 1px solid red;
    }
    .right{
        border: 1px solid black;
        display: table-cell;
    }
</style>
<div class="parent">
    <div class="left">1</div>
    <div class="right">2</div>
    <div class="right">3</div>
</div>
```

- flex
```html
<style>
    .parent {
        border: 2px dashed blue;
        display: flex;
        width: 100%;
    }


    .left{
        width: 100px;
        border: 1px solid red;
    }
    .right{
        border: 1px solid black;
        flex: 1;
    }
</style>
<div class="parent">
    <div class="left">1</div>
    <div class="right">2</div>
    <div class="right">3</div>
</div>
```
### 并排等分，单排对齐靠左布局
```html
<style>
    .parent {
        border: 2px dashed blue;
        display: flex;
        flex-flow: row wrap;
        justify-content: space-between;
    }


    .item{
        display: inline-block;
        border: 1px solid red;
        width: 100px;
    }
</style>
<div class="parent">
    <div class="item">1</div>
    <div class="item">2</div>
    <div class="item">3</div>
</div>
```
### 圣杯布局
```html
<style>
    .container {margin: 50px auto;}
    .wrapper {padding: 0 100px 0 100px;}
    .col {position: relative; float: left;}
    .header,.footer {height: 50px;background-color: red}
    .main {width: 100%;height: 200px;}
    .left {width: 100px; height: 200px; margin-left: -100%;left: -100px;background-color: yellow}
    .right {width: 100px; height: 200px; margin-left: -100px; right: -100px;background-color: black}
    .clearfix::after {content: ""; display: block; clear: both; visibility: hidden; height: 0; overflow: hidden;}</style>
<div class="container">
    <div class="header">header</div>
    <div class="wrapper clearfix">
        <div class="main col">main</div>
        <div class="left col">left</div>
        <div class="right col">right</div>
    </div>
    <div class="footer">footer</div>
</div>
```

### 双飞翼布局
```html
<style>
    .col {float: left;}
    .header {height: 50px;border: 1px solid red}
    .main {width: 100%;}
    .main-wrap {margin: 0 100px 0 100px;height: 200px;}
    .left {width: 100px; height: 200px; margin-left: -100%;background-color: silver}
    .right {width: 100px; height: 200px; margin-left: -100px;background-color: red}
    .footer {height: 50px;border: 1px solid red}
    .clearfix::after {content: ""; display: block; clear: both; visibility: hidden; height: 0; overflow: hidden;}
</style>
<div class="container">
    <div class="header">header</div>
    <div class="wrapper clearfix">
        <div class="main col">
            <div class="main-wrap">main</div>
        </div>
        <div class="left col">left</div>
        <div class="right col">right</div>
    </div>
    <div class="footer">footer</div>
</div>
```

### 定位布局
```html
<style>
    .wrapper { position: relative;background-color: black }
    .main { margin:0 100px;background-color: #00acec}
    .left { position: absolute; left: 0; top: 0;background-color: yellow}
    .right { position: absolute; right: 0; top: 0;background-color: silver}
</style>
<div class="header">header</div>
<div class="wrapper">
    <div class="main col">
        main
    </div>
    <div class="left col">
        left
    </div>
    <div class="right col">
        right
    </div>
</div>
<div class="footer">footer</div>
```

## 伪类实现垂直居中原理
[参考文献](https://www.zhangxinxu.com/wordpress/2010/09/after%E4%BC%AA%E7%B1%BBcontent%E5%86%85%E5%AE%B9%E7%94%9F%E6%88%90%E5%B8%B8%E8%A7%81%E5%BA%94%E7%94%A8%E4%B8%BE%E4%BE%8B/)
- :after伪类+content清除浮动的影响
```html
<style>
    .box {
        padding: 10px;
        background: gray;
    }

    .l {
        float: left;
    }
    .box:after{display:block; content:"clear"; height:0; clear:both; overflow:hidden; visibility:hidden;}
</style>


<div class="box">
    <img class="l" src="https://youimg1.c-ctrip.com/target/100h180000013qm0m8FCA_C_400_400_Q90.jpg"/>
</div>
```
- :after伪类+content实现垂直居中
```html
<style>
    .pic_box {
        width: 800px;
        height: 800px;
        background-color: #beceeb;
        font-size: 0;
        *font-size: 200px;
        text-align: center;
    }

    .pic_box img {
        vertical-align: middle;
    }

    .pic_box:after {
        display: inline-block;
        width: 0;
        height: 100%;
        content: "center";
        vertical-align: middle;
        overflow: hidden;
    }
</style>


<div class="pic_box">
    <img class="l" src="https://youimg1.c-ctrip.com/target/100h180000013qm0m8FCA_C_400_400_Q90.jpg"/>
</div>
```
